---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - common

- name: configure webserver
  hosts: webservers
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - web

- name: configure dbserver
  hosts: dbservers
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - db
