---
- name: create databases
  mysql_db:
    login_user=root
    login_password="{{ mysql_vars.mysql_root_password }}"
    name="{{ item }}"
    state=present
  with_items: "{{mysql_vars.databases}}"

- name: add users to databases
  mysql_user:
    login_user=root
    login_password="{{ mysql_vars.mysql_root_password }}"
    name="{{ item.key }}"
    password="{{ item.value.password }}"
    priv={{ item.value.priv }}
    state={{ item.value.state | default('present') }}
  with_dict: "{{mysql_vars.users}}"
