---
- name: install mysql
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - python-mysqldb

- name: set root password
  mysql_user:
    name="root"
    password="{{ mysql_vars.mysql_root_password }}"
    priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: create mysql config file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: delete anonymous MySQL server user
  action:
    mysql_user
    login_user=root
    login_password="{{ mysql_vars.mysql_root_password }}"
    user=""
    host="{{ item }}"
    state=absent
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: remove the MySQL test database
  action:
    mysql_db
    login_user=root
    login_password="{{ mysql_vars.mysql_root_password }}"
    db=test
    state=absent