---
# set up phpmyadmin
- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{mysql_vars.mysql_root_password}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{mysql_vars.mysql_root_password}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{mysql_vars.mysql_root_password}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

- name: install pma
  apt: pkg=phpmyadmin state=present

- name: configure site
  file: path=/var/www/html/phpmyadmin src=/usr/share/phpmyadmin state=link